# ChatMe/docker-compose.yml
services:
  redis:
    image: redis/redis-stack:latest
    container_name: chatme-redis
    environment:
      - REDIS_ARGS=--requirepass 123456
    volumes:
      - ./docker_data/redis-stack/data:/data
      - ./docker_data/redis-stack/redisinsight:/var/lib/redisinsight
    ports:
      - "6024:6379"
      - "28001:8001"
    restart: unless-stopped
    networks:
      - chatme-net

  sandbox:
    build:
      context: . # 项目根
      dockerfile: sandbox/Dockerfile
    image: chatme-python-sandbox:latest
    profiles:
      - never  # 不会自动启动，按需手动运行

networks:
  chatme-net:
    driver: bridge
